name: Integration Test CI

on:
  push:
    branches:
      - main
      - staging
      - development
  pull_request:
    branches:
      - main
      - staging
      - development
      - feature/*

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run integration tests
    - name: Run integration tests
      run: npm run test

    - name:  Check code coverage
      run: npm run test:coverage